# -*- coding: utf-8 -*-
"""Visualisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wxm_xej5ZI5CVljEAnjU3V4Zjr03l3_u
"""

from celluloid import Camera as Camera
import matplotlib.pyplot as plt
import pandas as pd
from random import randint
import re
from tqdm import trange

print("Введите путь до исходного файла:")
input_dir = input()
data = pd.read_csv(input_dir)
start = input_dir.rfind('/')
end = input_dir.rfind('.')
filename = input_dir[start + 1:end]
num = int(re.findall(r'\d+',filename)[0])

color = []
for i in range(num):
    color.append('#%06X' % randint(0, 0xDDDDDD))

masses = data['mass'][:num]

fig = plt.figure()
camera = Camera(fig)

fig.set_size_inches(5, 5)
ax1 = fig.add_subplot()
ax1.set_title("Dot Simulation")
ax1.grid(1)

for i in trange(0, len(data['x']), num):
  ax1.scatter(x = data['x'][i:i+num], y = data['y'][i:i+num], s = masses, c = color)
  camera.snap()

print('Animating...')
animation = camera.animate()
print('Saving animation...')
animation.save("./data/output/test1.avi")
print('OK!')
