# -*- coding: utf-8 -*-
"""visualisation_metrics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Un6VflFUv3UKYr-PvDDm5fmS5GfHhqIl
"""

import seaborn as sns
import pandas as pd
import numpy as np

print("Введите путь до исходного файла:")
input_dir = input()
data = pd.read_csv(input_dir)

sns.set_theme(style="whitegrid")
bodies = sns.catplot(
    data=data, kind="bar",
    x="n_threads", y="mean_comp_time", hue="n_bodies",
    errorbar="sd", palette="dark", height=10
)

threads = sns.catplot(
    data=data, kind="bar",
    x="n_bodies", y="mean_comp_time", hue="n_threads",
    errorbar="sd", palette="dark",height=10
)

